CREATE TABLE productos
(
    producto_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
        PRIMARY KEY,
    nombre  VARCHAR2( 255 ) NOT NULL,
    precio NUMBER( 9, 2 ) NOT NULL       ,
    cantidad_almacen NUMBER (9,0) NOT NULL,
    fecha_caducidad Date NOT NULL
);